version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=VillaListRazor;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=True
